### ISSUE TITLE
Add Jedi logo for project

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#14]

**Comment by gdtrombetti** [comment]
Hello,  where would you like the logo to be added? and where can I obtain this logo?

**Comment by dmitriytat** [comment]
@gdtrombetti it did not created yet:)

**Comment by Jarleborn** [comment]
I added a Jedi logo 
[PR](https://github.com/dimkosru/jedi-validate/pull/26)

**Comment by dmitriytat** [comment]
@hj222hi thanks
