### ISSUE TITLE
Style the example page

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#15]

**Comment by amandaporto** [comment]
I'd like to help out with the example page. Any specific details about how you'd like it styled? (Also, I'm assuming when you refer to "page" you mean the README file, since I couldnt find a website anywhere. Correct me if I'm wrong.)

**Comment by dmitriytat** [comment]
@amandaporto Hello! I mean /example/bootstrap.html you can open it on webpack-dev-server (`npm run dev`) or run your own server for example `python -m SimpleHTTPServer`

**Comment by amandaporto** [comment]
Ah cool cool! I'll do it tonight then!

**Comment by dmitriytat** [comment]
@mithun-daa thanks for styling example page
