### ISSUE TITLE
Need README review

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#18]
I have merged two commits with English remarks. But last was with conflicts. And I resolve it by myself. I do not sure about result quality.

Help me with it.)

**Comment by virenderkadyan** [comment]
i would like to help u ..let me know

**Comment by dmitriytat** [comment]
@drsumanpreet ok. It would be good.

**Comment by matturenovich** [comment]
Thanks for merging my PR #22

**Comment by palash-taneja** [comment]
Reviewed and corrected at a couple of  places. #23
