### ISSUE TITLE
Create implementation for adding custom texts in i18n dictionary.

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#19]
Need a method which will add text to dictionary.

**Comment by rdbatch** [comment]
What were you looking at as a use case for this? Some way to programmatically add translations at runtime or would it be an interface to save to the .json dictionary?

**Comment by dmitriytat** [comment]
@c1phr at runtime, i think because rules are added at runtime. Maybe it is not necessary at all.

**Comment by rdbatch** [comment]
I could still envision giving users the option to add one-off translations at runtime rather than always forcing them to add translations to the .json file. I'll take a crack at this in the next day or two and see what you think.

**Comment by dmitriytat** [comment]
@c1phr how developer will use it with json file? I think end user dont need to build class.

**Comment by rdbatch** [comment]
I was thinking just combine whatever rules are already in the JSON file with any rules that are added at runtime.

**Comment by dmitriytat** [comment]
@c1phr ok, I understand you now. It is a good idea.

**Comment by rdbatch** [comment]
I've added PR #25 that addresses this and adds the ability to set the language on the JediValidate constructor. Let me know if this works or if you were hoping for something different.
