### ISSUE TITLE
Fix code style errors.

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#27]
I added eslint with airbnb style guide. Need to fix errors.

**Comment by jamesmacfie** [comment]
I can help out here if you like

**Comment by dmitriytat** [comment]
@jamesmacfie it would be good

**Comment by jamesmacfie** [comment]
Is there any reason why there is both an `.eslintrc` file and also a `.eslintrc.json` file?

**Comment by dhruvdutt** [comment]
I believe `.eslintrc.json` would get precedence because the order is:

```
.eslintrc.js
.eslintrc.yaml
.eslintrc.yml
.eslintrc.json
.eslintrc
package.json
```

**Comment by dmitriytat** [comment]
@jamesmacfie @mithun-daa thank you! for-in i will rewrite on map or reduce

**Comment by ghost** [comment]
Can I still work on this?

**Comment by dmitriytat** [comment]
@vincealdrin yep on `dev` brunch please.
