### ISSUE TITLE
Fix get data from radio button group

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#33]
Now in dev brunch on example/bottstrap.html value can not be sent.

**Comment by vikashvverma** [comment]
@dimkosru Can you elaborate a bit, I would like to help?

**Comment by dmitriytat** [comment]
@vikashvverma now i rework internal data structure. And i noticed that getData function does not get value of radiogroup. problem maybe with getData or converData function, maybe with getRadioGroupValue.

It will be great if you also write test for this case)

**Comment by dmitriytat** [comment]
@vikashvverma i fixed this bug
