### ISSUE TITLE
Add support of input with type="number" 

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#58]
Add new functions for input attributes **min**, **max** and **step** to [methods](https://github.com/dmitriytat/jedi-validate/blob/master/src/lib/methods.js).

Check how to change and change [getInputRules](https://github.com/dmitriytat/jedi-validate/blob/master/src/lib/get-options.js#L24) function.

And in additional (or at first if you use TDD) add [tests](https://github.com/dmitriytat/jedi-validate/blob/master/tests/methods.js).

**Comment by ghosh** [comment]
I can pick this up. I'll submit a PR soon.

**Comment by ghosh** [comment]
@dmitriytat I'm working on this now. I set up the **min** and **max** functions in methods.

 I have a question though, how do I access the values of the min and max attributes in the function? Do I have to pass them in explicitly in the options object while calling JediValidate?

**Comment by dmitriytat** [comment]
@ghosh We have two ways to do this:

1. Get options from input attributes by [getInputRules](https://github.com/dmitriytat/jedi-validate/blob/master/src/lib/get-options.js#L24) functions.
2. Use options object.

In first case we check attributes and add rule to options. You can add it like it was added for **pattern** attribute [this](https://github.com/dmitriytat/jedi-validate/blob/master/src/lib/get-options.js#L41).

**Comment by ghosh** [comment]
Thanks. This makes sense. Fixed in #61.

Can this be closed now?

**Comment by dmitriytat** [comment]
Yep
