### ISSUE TITLE
Add babel-preset-env

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#65]
last 2 versions, ie 10

**Comment by thedeany** [comment]
I can take this. I'm only slightly familiar with `babel-preset-env`, so my only question is that it fully replaces the `babel-preset-es2015` and `babel-preset-stage-3` dependencies, correct? I'll remove those as dependencies if so.

**Comment by dmitriytat** [comment]
@thedeany yep, it is correct
