### ISSUE TITLE
Add validator methods description to README

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#69]
Check and improve the description of validation methods in README.

https://github.com/dmitriytat/jedi-validate/blob/master/src/lib/methods.js

**Comment by indirap** [comment]
Hey, I'd love to help out with this. I'll submit a pull-request shortly.

**Comment by indirap** [comment]
Hey @dmitriytat, I'm trying to push my branch to origin but keep getting this error message:
```
Pushing to https://github.com/dmitriytat/jedi-validate.git
remote: Permission to dmitriytat/jedi-validate.git denied to indirap.
fatal: unable to access 'https://github.com/dmitriytat/jedi-validate.git/': The requested URL returned error: 403
```

I don't use Github much at all and this is my first time contributing to an open-source project so I'm not sure what's going on; do I need some kind of special permissions? Let me know, thanks!

**Comment by indirap** [comment]
Silly me, I cloned your repo instead of forking it and then cloning it. I've created a pull-request. 🙂
