### ISSUE TITLE
Add support of accept attribute for file input

### ISSUE THREAD

**Issue by dmitriytat** [dmitriytat/jedi-validate#72]
Now we have [extension rule](https://github.com/dmitriytat/jedi-validate/tree/development#extension).
We need to get options from accept attribute like [here](https://github.com/dmitriytat/jedi-validate/tree/development#basic-rules)

from
```
<input type="file" accept=".csv" />
```
to
```
file: {
    extension: "csv"
}
```

Add functionality [here](https://github.com/dmitriytat/jedi-validate/blob/development/src/lib/get-options.js#L24)
Add test [here](https://github.com/dmitriytat/jedi-validate/blob/development/tests/get-options.js#L49)
Add example [here](https://github.com/dmitriytat/jedi-validate/blob/development/example/bootstrap.html#L75) and in [README](https://github.com/dmitriytat/jedi-validate/blob/development/README.md#basic-rules)

Contribute to **development** branch

**Comment by batoreh** [comment]
Assign this to me, please.

**Comment by dmitriytat** [comment]
@netoguimaraes I think that your message is enough)

**Comment by batoreh** [comment]
Okay, thanks

**Comment by batoreh** [comment]
@dmitriytat When receiving
```html
    <input type="file" accept="audio/*" />
```
should return 
```javascript
file: {
    extension: "audio"
}
```
or

```javascript
file: {
    extension: ["mp3", "wav", "ogg", ...extensions]
}
```
or what?

**Comment by dmitriytat** [comment]
@netoguimaraes, you can implement simple case with extensions only.
Or, maybe, create new rule **accept** with paramenters like in input (`audio/*` and other) and implement new validation method for this case.

**Comment by batoreh** [comment]
Okay, @dmitriytat. I will take a look in what I can do and then send a PR.

**Comment by dmitriytat** [comment]
@netoguimaraes thank you
